### ISSUE TITLE
import pymt command gives traceback message about Netcdf library incompatibility

### ISSUE THREAD

**Issue by iovereem** [csdms/pymt#72]
Following the instructions on the installation page: 
https://pymt.readthedocs.io/en/latest/installation.html

If I type the 'import pymt' command, I get a error message, that has to do with the fact that there is still Python 2.7 installation on my machine?

Here is the message: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/overeem/anaconda/lib/python2.7/site-packages/pymt/__init__.py", line 6, in <module>
    from .plugin import load_pymt_plugins
  File "/Users/overeem/anaconda/lib/python2.7/site-packages/pymt/plugin.py", line 42, in <module>
    from .framework.bmi_bridge import bmi_factory
  File "/Users/overeem/anaconda/lib/python2.7/site-packages/pymt/framework/bmi_bridge.py", line 10, in <module>
    from cfunits import Units
  File "/Users/overeem/anaconda/lib/python2.7/site-packages/cfunits/__init__.py", line 35, in <module>
    from .units import Units
  File "/Users/overeem/anaconda/lib/python2.7/site-packages/cfunits/units.py", line 4, in <module>
    import netCDF4
  File "/Users/overeem/anaconda/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/overeem/anaconda/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /Users/overeem/anaconda/lib/python2.7/site-packages/netCDF4/_netCDF4.so
  Reason: Incompatible library version: _netCDF4.so requires version 10.0.0 or later, but libcurl.4.dylib provides version 9.0.0

**Comment by mdpiper** [comment]
Fixed with [gimli.units](https://github.com/mcflugen/gimli).
