### ISSUE TITLE
Support structured quadrilateral grid type

### ISSUE THREAD

**Issue by mdpiper** [csdms/pymt#88]
The [BMI documentation](https://bmi.readthedocs.io/en/latest/bmi.grid_funcs.html) lists `structured_quadrilateral` as a valid grid type, but it's not available in pymt. For example:

```
Traceback (most recent call last):
  File "fastmech_pymt_ex.py", line 25, in <module>
    m.initialize(*defaults)
  File "/home/mpiper/anaconda3/envs/wrap/lib/python3.6/site-packages/pymt/framework/bmi_bridge.py", line 200, in initialize
    self._grid[grid_id] = dataset_from_bmi_grid(self, grid_id)
  File "/home/mpiper/anaconda3/envs/wrap/lib/python3.6/site-packages/pymt/framework/bmi_ugrid.py", line 31, in dataset_from_bmi_grid
    raise ValueError("grid type not understood ({gtype})".format(gtype=grid_type))
ValueError: grid type not understood (structured_quadrilateral)
```

**Comment by mdpiper** [comment]
@mcflugen Looking at your code in pymt/framework/bmi_ugrid.py, I think I can do this. I'd base the grid on a Landlab StructuredQuadGraph.
